version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: to_livre_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d to_livre_test"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
